#trigger:
#  batch: true
#  branches:
#    include:
#      - master
#  paths:
#    include:
#      - '*'
#
#pr:
#  branches:
#    include:
#      - '*'

trigger: none
pr: none

variables:
  - name: TF_LOG
    value: INFO
  - name: WORKING_DIR
    value: '$(System.DefaultWorkingDirectory)'
  - group: 'PUBLIC_KEY' # keeps: known_hosts, id_rsa.pub, id_rsa

stages:
  - stage: "Terraform_CI"
    displayName: "Terraform Validate"
    jobs:
      - job: Terraform_CI
        displayName: "Terraform Validate"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 0

          - task: TerraformInstaller@0
            displayName: 'Terraform Installer'
            inputs:
              terraformVersion: 'latest'

          - script: terraform -v
            displayName: 'Terraform Version'
            workingDirectory: '$(WORKING_DIR)'

          - task: InstallSSHKey@0
            displayName: 'Install an SSH key'
            inputs:
              knownHostsEntry: '$(known_hosts)'   # known_hosts file contents from local machine after 'ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts'
              sshPublicKey: '$(id_rsa.pub)'       # public key plain text from library
              sshKeySecureFile: 'id_rsa'          # private key from secure files

          - script: terraform init -backend=false
            displayName: 'Terraform Init'
            workingDirectory: '$(WORKING_DIR)'

          - script: terraform validate
            displayName: 'Terraform Validate'
            workingDirectory: '$(WORKING_DIR)'

          - script: terraform fmt -check
            displayName: 'Terraform Format'
            workingDirectory: '$(WORKING_DIR)'
